### ISSUE TITLE
Add `humans.txt`

### ISSUE THREAD

**Issue by ndorfin** [starshyyne/lauramunro.nz#19]
I love this little initiative.

See [humanstxt.org](https://humanstxt.org/)

- [x] Add a `humans.txt` in the webroot of your site. Fill it with love.

**Comment by starshyyne** [comment]
I was looking for an easy task to do tonight, and so started this file: https://github.com/starshyyne/lauramunro.nz/blob/humans/humans.txt if you could take a look and let me know if you're happy for me to include your information, if there's any additional info you'd like there :)

**Comment by ndorfin** [comment]
That's a pleasant surprise, thank you!
